apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-db
  name: postgres-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-db
    spec:
      containers:
      - image: postgres
        name: postgres-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db-claim0
      restartPolicy: Always
      volumes:
      - name: postgres-db-claim0
        persistentVolumeClaim:
          claimName: postgres-db-claim0
status: {}
