default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
database: postgres-db_development

test:
  <<: *default
database: postgres-db_test

production:
  <<: *default
  database: postgres-db_production
  username: user
password: <%= ENV['PODTGRED-DB_DATABASE_PASSWORD'] %>
